[2023-10-17T14:46:20.442+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stores_pipeline.reading_and_preprocessing.join_sales_stores scheduled__2023-10-16T00:00:00+00:00 [queued]>
[2023-10-17T14:46:20.444+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stores_pipeline.reading_and_preprocessing.join_sales_stores scheduled__2023-10-16T00:00:00+00:00 [queued]>
[2023-10-17T14:46:20.444+0100] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-17T14:46:20.448+0100] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): reading_and_preprocessing.join_sales_stores> on 2023-10-16 00:00:00+00:00
[2023-10-17T14:46:20.450+0100] {standard_task_runner.py:57} INFO - Started process 57986 to run task
[2023-10-17T14:46:20.452+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'stores_pipeline', 'reading_and_preprocessing.join_sales_stores', 'scheduled__2023-10-16T00:00:00+00:00', '--job-id', '329', '--raw', '--subdir', 'DAGS_FOLDER/stores_pipeline.py', '--cfg-path', '/var/folders/_3/bj8r7kz51nz4g7hl_dpr6jdw0000gn/T/tmpatfmz8pd']
[2023-10-17T14:46:20.453+0100] {standard_task_runner.py:85} INFO - Job 329: Subtask reading_and_preprocessing.join_sales_stores
[2023-10-17T14:46:20.472+0100] {task_command.py:416} INFO - Running <TaskInstance: stores_pipeline.reading_and_preprocessing.join_sales_stores scheduled__2023-10-16T00:00:00+00:00 [running]> on host 192.168.1.112
[2023-10-17T14:46:20.488+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='workflow' AIRFLOW_CTX_DAG_ID='stores_pipeline' AIRFLOW_CTX_TASK_ID='reading_and_preprocessing.join_sales_stores' AIRFLOW_CTX_EXECUTION_DATE='2023-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-16T00:00:00+00:00'
[2023-10-17T14:46:20.497+0100] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/b/airflow/venv/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/b/airflow/venv/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/b/airflow/dags/stores_pipeline.py", line 78, in join_sales_stores
    join_data = pd.merge (
                ^^^^^^^^^^
  File "/Users/b/airflow/venv/lib/python3.11/site-packages/pandas/core/reshape/merge.py", line 151, in merge
    left_df = _validate_operand(left)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/b/airflow/venv/lib/python3.11/site-packages/pandas/core/reshape/merge.py", line 2626, in _validate_operand
    raise TypeError(
TypeError: Can only merge Series or DataFrame objects, a <class 'str'> was passed
[2023-10-17T14:46:20.500+0100] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=stores_pipeline, task_id=reading_and_preprocessing.join_sales_stores, execution_date=20231016T000000, start_date=20231017T134620, end_date=20231017T134620
[2023-10-17T14:46:20.504+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 329 for task reading_and_preprocessing.join_sales_stores (Can only merge Series or DataFrame objects, a <class 'str'> was passed; 57986)
[2023-10-17T14:46:20.514+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-17T14:46:20.523+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
