[2023-10-15T16:46:35.298+0100] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute.taskA manual__2023-10-15T15:46:32.704513+00:00 [queued]>
[2023-10-15T16:46:35.302+0100] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute.taskA manual__2023-10-15T15:46:32.704513+00:00 [queued]>
[2023-10-15T16:46:35.302+0100] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-10-15T16:46:35.302+0100] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-10-15T16:46:35.302+0100] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-10-15T16:46:35.306+0100] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): taskA> on 2023-10-15 15:46:32.704513+00:00
[2023-10-15T16:46:35.308+0100] {standard_task_runner.py:55} INFO - Started process 45001 to run task
[2023-10-15T16:46:35.311+0100] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'execute', 'taskA', 'manual__2023-10-15T15:46:32.704513+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/__pycache__/execute.py', '--cfg-path', '/var/folders/_3/bj8r7kz51nz4g7hl_dpr6jdw0000gn/T/tmp4tn0liuv']
[2023-10-15T16:46:35.316+0100] {standard_task_runner.py:83} INFO - Job 25: Subtask taskA
[2023-10-15T16:46:35.346+0100] {task_command.py:389} INFO - Running <TaskInstance: execute.taskA manual__2023-10-15T15:46:32.704513+00:00 [running]> on host 192.168.1.112
[2023-10-15T16:46:35.362+0100] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=workflow
AIRFLOW_CTX_DAG_ID=execute
AIRFLOW_CTX_TASK_ID=taskA
AIRFLOW_CTX_EXECUTION_DATE=2023-10-15T15:46:32.704513+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-15T15:46:32.704513+00:00
[2023-10-15T16:46:35.362+0100] {subprocess.py:63} INFO - Tmp dir root location: 
 /var/folders/_3/bj8r7kz51nz4g7hl_dpr6jdw0000gn/T
[2023-10-15T16:46:35.363+0100] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo TASK A has started!\n\nfor i in {1..15}\ndo\n    echo "TASK A: $i"\n    sleep 10\ndone\n\necho TASK A has finished!']
[2023-10-15T16:46:35.365+0100] {subprocess.py:86} INFO - Output:
[2023-10-15T16:46:35.367+0100] {subprocess.py:93} INFO - TASK A has started!
[2023-10-15T16:46:35.368+0100] {subprocess.py:93} INFO - TASK A: 1
[2023-10-15T16:46:45.380+0100] {subprocess.py:93} INFO - TASK A: 2
[2023-10-15T16:46:55.390+0100] {subprocess.py:93} INFO - TASK A: 3
[2023-10-15T16:47:05.401+0100] {subprocess.py:93} INFO - TASK A: 4
[2023-10-15T16:47:15.414+0100] {subprocess.py:93} INFO - TASK A: 5
[2023-10-15T16:47:25.424+0100] {subprocess.py:93} INFO - TASK A: 6
[2023-10-15T16:47:35.442+0100] {subprocess.py:93} INFO - TASK A: 7
[2023-10-15T16:47:42.447+0100] {process_utils.py:129} INFO - Sending 15 to group 45001. PIDs of all processes in the group: [45002, 45068, 45001]
[2023-10-15T16:47:42.448+0100] {process_utils.py:84} INFO - Sending the signal 15 to group 45001
[2023-10-15T16:47:42.448+0100] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-15T16:47:42.449+0100] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2023-10-15T16:47:42.460+0100] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/b/airflow/venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 187, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/b/airflow/venv/lib/python3.11/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/Users/b/airflow/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 1490, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-10-15T16:47:42.465+0100] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=execute, task_id=taskA, execution_date=20231015T154632, start_date=20231015T154635, end_date=20231015T154742
[2023-10-15T16:47:42.472+0100] {standard_task_runner.py:100} ERROR - Failed to execute job 25 for task taskA (Task received SIGTERM signal; 45001)
[2023-10-15T16:47:42.482+0100] {process_utils.py:79} INFO - Process psutil.Process(pid=45002, status='terminated', started='16:46:35') (45002) terminated with exit code None
[2023-10-15T16:47:42.483+0100] {process_utils.py:79} INFO - Process psutil.Process(pid=45068, status='terminated', started='16:47:35') (45068) terminated with exit code None
[2023-10-15T16:47:42.483+0100] {process_utils.py:79} INFO - Process psutil.Process(pid=45001, status='terminated', exitcode=1, started='16:46:35') (45001) terminated with exit code 1
